### ISSUE TITLE
Java 9 Support

### ISSUE THREAD

**Issue by Zbob750** [PaperMC/Paperclip#10]
Paperclip will not run on Java 9 due to the changes made by[ JEP-220](http://openjdk.java.net/jeps/220)

```SystemClassLoader not URLClassLoader```

**Comment by josephworks** [comment]
java 9 has not been officially released and moet minecraft plugins (for now) require java 8

**Comment by DemonWav** [comment]
...that is true and irrelevant.

**Comment by ysl3000** [comment]
The bug happens on buildtools, too. I updated the ASM dependency and it did the job quiet well. 
BuildTools > ASM > a dependency that caused the bug. 
New beta version of ASM works.

**Comment by IsaiahPatton** [comment]
![image](https://user-images.githubusercontent.com/16439221/30522611-01c1d6cc-9ba1-11e7-9e52-c57b3b68a695.png)

**Comment by josephworks** [comment]
https://java.com/en/download/

**Comment by DemonWav** [comment]
We are very aware.

**Comment by josephworks** [comment]
if that switches to Java 9 then we can worry.

**Comment by josephworks** [comment]
lol

**Comment by DemonWav** [comment]
Fixed in c562261.

**Comment by DemonWav** [comment]
Whoops this isn't fixed.

**Comment by DemonWav** [comment]
This is actually fixed now.
