### ISSUE TITLE
Various Java classloader compatibility problems

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paperclip#11]
Some plugins tinker with the classpath or access it in non-standard ways that are incompatible with Paperclip's methods.

This ticket exists to track plugin compatibility problems and any solutions as they appear.
It does not exist to handle Java 9 classloader issues or any plugin compatibility issues that are also present running just Paper-Server without Paperclip.

**Comment by josephworks** [comment]
that's the plugins fault, not paper's fault. If "Some plugins tinker with the classpath or access it in non-standard ways that are incompatible with Paperclip's methods." is a problem with spigot then don't worry about it.

**Comment by DemonWav** [comment]
Depends on the situation.

**Comment by DemonWav** [comment]
We've had approximately 0 real issues related to this for 2 years so I'll consider this a moot point now. If particular issues arise we can deal with them individually.
