### ISSUE TITLE
[Request] Add possibility to decide which version is built

### ISSUE THREAD

**Issue by Panossa** [PaperMC/Paperclip#12]
My server is working with jenkins to build the newest version of 1.12 spigot every day if there's an update. When spigot is updated to 1.13 jenkins will still fetch the 1.12 version. Would be cool if Paper had the same. But I can't find a possibility to get rid of a future 1.13 paper build without looking into the completely build jar via shell script AFTER it has been built.

**Comment by Zbob750** [comment]
Paperclip only bundles a single version of Paper, it does not download any versions or contact any Paper servers in any way. This feature request is outside the scope of Paperclip.

Which for anyone unaware is:
To allow us to safely distribute a single version of Paper-Server using a single binary patch included in the paperclip.jar people download.
