### ISSUE TITLE
Replace or remove java 6 module

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Paperclip#16]
See https://github.com/PaperMC/Paper/issues/2179

java 12 dropped support for java 6, so its not possible to compile paperclip with java 12+.
two options: either that module can be remove or should be bumped up to 7.

**Comment by mikroskeem** [comment]
_But muh legacy???_

I think that's fine, most of the modern OS-es don't even offer Java 6 easily afaik.

**Comment by MiniDigger** [comment]
@mikroskeem, to only point of that module is to yell at ppl to install Java 8+ 😂
So if they manage to install Java 6 and we dropped that module, they get an obscure error message instead.

**Comment by zachbr** [comment]
There’s a PR for this at GH-15

Will probably fast track that this weekend and get paper repos updated with a newer version
