### ISSUE TITLE
Java 11

### ISSUE THREAD

**Issue by exin12** [PaperMC/Paperclip#28]
Hello

and that is I cannot start PaperMC with Java argument "-classpath" in Java OpenJDK 11 in Debian 10 I get the following error message:

`mc@mc:~/mc# java -cp '/server/services/version/paper-1.16.4-318.jar:lib/*' io.papermc.paperclip.Paperclip nogui --world-dir worlds
Patching vanilla jar...
Unable to retrieve Instrumentation API to add Paper jar to ClassPath
mc@mc:~/mc#
`

`mc@mc:~/mc# java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
`

 in Java 8 it went without problems

with the Java argument "-jar ..." it works without problems.

**Comment by electronicboy** [comment]
on newer versions of java, we use an agent to allow us to hook into the classloader to boot the patched server jar without breaking plugins, etc;
You'll need to add the agent manually, or launch the server with -jar, pretty sure that works with -cp too, `Launcher-Agent-Class: io.papermc.paperclip.Agent`
