### ISSUE TITLE
[Request] Init command to prepare jar and dir structure

### ISSUE THREAD

**Issue by MichaIng** [PaperMC/Paperclip#32]
In some cases, it is great to have some sort of init command, which downloads, patches and installs the jar, prepares the directory structure and configuration files, but does not start the actual Minecraft server. That way it can be pre-configured, plugins installed first etc, e.g. for scripting the whole install and setup process, which is the aim our end.

Looks like here an additional option could be checked for, before running the patched jar: https://github.com/PaperMC/Paperclip/blob/master/java8/src/main/java/io/papermc/paperclip/Paperclip.java#L53

Best would be if even the Minecraft server's and plugins' own default configuration files could be pre-created, but I guess that would be much more complicated, including additional patches to the vanilla jar if those do not have such an option already.

**Comment by electronicboy** [comment]
Paperclip is a bootstrap tool, such a configuration option would *need* to start the server in order to run the relevant code to actually create the configuration files, any option for this would really need to be in the server itself, which, I can't see there being a huge demand for at all, too nuanced for such a marginal use-case

**Comment by MichaIng** [comment]
Ah okay, I see now that I mixed up `paperclip.properties` with `server.properties` indeed, so I'll reopen on the server repo.

**Comment by electronicboy** [comment]
for what you're wanting, especially if you want plugins configs to be created, you'd actually need to start all the plugins and everything, sounds like the best option would be to just have a shim plugin which stops the server after startup

**Comment by MichaIng** [comment]
I'm not sure how the main server init is structured, but there will be some init step where the plugins have been loaded, before the server binds to a port, the world and spawn areas are created etc, like between those two steps:
```
Jan 06 18:02:17 VM-Buster papermc[5382]: [18:02:17 INFO]: Generating keypair
Jan 06 18:02:18 VM-Buster papermc[5382]: [18:02:18 INFO]: Starting Minecraft server on *:25565
```
Not sure how to archive this best, making it part of the patches or as a plugin. But I'm currently opening a request at the Paper repo, where it indeed fits better.

**Comment by electronicboy** [comment]
loaded != enabled, plugins need to be enabled to create their configs, which requires going past the point of having loaded the worlds

**Comment by MichaIng** [comment]
Ah okay, I guess different aims of this could then conflict, e.g. if someone wants or needs to have the server binding to a different port initially, it needs to stop before this step, but then plugin configs do not exist yet. Okay I see that it is not that trivial, let's see if there is even any interest for such by others and their use case.
