### ISSUE TITLE
More useful output when Java Instrumentation API is missing

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paperclip#33]
Some distributions of Java do not include the instrumentation module with their VM image.

It would be helpful if we could print some vendor information about the current JVM along with the message so when they come and ask for help we can more quickly spot it.

edit: OpenJDK mailing list discussion of the possible exclusion of instrumentation apis
http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-May/012702.html

**Comment by DenWav** [comment]
As of MC 1.18 Paperclip no longer uses the Instrumentation API
