### ISSUE TITLE
Unable to retrieve Instrumentation API to add Paper jar to classpath. If you're running paperclip without -jar then you also need to include the -javaagent:<paperclip_jar> JVM command line option.

### ISSUE THREAD

**Issue by DanteDFF** [PaperMC/Paperclip#34]
Hi,
i always get this Warning when im starting my Server
on Deb10
and java11
"Unable to retrieve Instrumentation API to add Paper jar to classpath. If you're running paperclip without -jar then you also need to include the -javaagent:<paperclip_jar> JVM command line option."

can someone help me please

**Comment by MiniDigger** [comment]
please include more info.
how do you start the server?

**Comment by DanteDFF** [comment]
i use the server in a cloud system
so with executing the jar i guess

**Comment by MiniDigger** [comment]
well, then its a bug in said "cloud" system, bring it up to them, they will know what to do with the error message

**Comment by Shevchik** [comment]
It's not a bug. JVM distribution is allowed not to have instrumentation API available. Launch paperclip locally, so it builds a paper jar (located in cache subdirectory) and use that for server.

**Comment by MiniDigger** [comment]
Are you sure? I looked at the source for a second and saw they use the instrumentation api to add their own Javaagent and stuff so i wouldn't be surprised if they broke stuff

**Comment by zachbr** [comment]
When people make their own JVM images, the instrumentation API is not required no. The “minimal” image does not include it for example.

There are some mailing list threads about this but it was never changed. Hence my other issue on this repo to provide more info when it happens.


http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-May/012702.html

**Comment by zachbr** [comment]
I don’t know that there’s any real fixing this as far as paperclip is concerned either.

We can provide the user and ourselves with more information and guide them to a more complete (read: better) image, but not like we can correct it.


Original author, if you need more assistance with this please seek support on the forums or discord. You can either run it locally and take the cached patch jar and use that remotely or you need a different distribution of Java.

**Comment by DanteDFF** [comment]
and how can i fix this?

**Comment by Proximyst** [comment]
> Original author, if you need more assistance with this please seek support on the forums or discord. You can either run it locally and take the cached patch jar and use that remotely or you need a different distribution of Java.

**Comment by DanteDFF** [comment]
So i can run the jar in a local server and then put the jar from the server after starting?

**Comment by electronicboy** [comment]
from the cache folder, yes
