### ISSUE TITLE
Paper fails to load if cache dir is a symlink - again

### ISSUE THREAD

**Issue by valderman** [PaperMC/Paperclip#47]
The exact same issue as in https://github.com/PaperMC/Paperclip/issues/18 is happening again with Paper 1.18.1 build 76.

**Comment by orbyfied** [comment]
This does not seem to fix the issue
`Files.isDirectory(...)` returns `false` when called on a sym link on Unix systems (unsure about Windows)
Why not just use `Files.exists(...)`, or at least pair current conditions with `&& !Files.isSymbolicLink(...)`

}
