### ISSUE TITLE
Plz add 1.19.2 support

### ISSUE THREAD

**Issue by MEMESCOEP** [PaperMC/Paperclip#58]
Can the devs add mc 1.19.2 support pls? I want to install it on my mc server but I can only use 1.19

**Comment by chickeneer** [comment]
1.19.2 support is already available. See https://papermc.io/downloads#Paper-1.19

**Comment by MEMESCOEP** [comment]
But when I update my mc server using a bash file or by running the jar file, it still runs 1.19 and not 1.19.2?

**Comment by electronicboy** [comment]
paperclip is basically just a magical bootstrap, it has no bearing on the version of MC; for support, please use the discord/forums/IRC, this is not the place for support with paper

**Comment by yannicklamprecht** [comment]
> But when I update my mc server using a bash file or by running the jar file, it still runs 1.19 and not 1.19.2?

Then update the jar file. By restarting it, it will not magically update to 1.19.2

**Comment by MEMESCOEP** [comment]
alr will try
