### ISSUE TITLE
/help not working properly? (Narrowing down my issue.)

### ISSUE THREAD

**Issue by Linebeck** [PaperMC/Paperclip#7]
So, I have set this customtext #help with a custom message. I added the alias in commands.yml, and made /help ---> customtext #help. So the problem is, recently it has been reverting to Essentials /help. I thought that commands.yml auto overrides everything by default. I reached out to the people developing EssentialsX to see if they knew a cause. If you could help me narrow this down or provide an explanation that would be great!

Thanks <3

(I am using the latest builds.)

**Comment by Zbob750** [comment]
This is not the appropriate place for this issue. Please use either the [Aquifer forums](aquifermc.org) or the [Paper server](https://github.com/PaperMC/Paper) issue tracker.

This tracker is for the launcher system, it is unrelated to your issue.

**Comment by Linebeck** [comment]
Oh ok. Sorry.
